### ISSUE TITLE
Simple instructions to use?

### ISSUE THREAD

**Issue by SB2020-eye** [VIROBO-15/UDBNET#2]
Hello. Your results (pictured in your paper) look great.

I am very, very new to coding and need the best binarization I can find for a medieval historical document.

Would you be able to provide me with simple instructions about or script for how I could try out UDBNET? For example, after downloading UDBNET, how would I binarize "ImageA.png"?

(For what it's worth, I am using a Windows 10 pc, Visual Studio Code, Python (in an Anaconda environment).)

**Comment by amandpkr** [comment]
you see the dataloader and pickle file

**Comment by SB2020-eye** [comment]
I see the `.pickle` file (though I confess I don't know what a pickle file is).

Which one is the dataloader file?

**Comment by amandpkr** [comment]
pickle file stories the list of the degraded image and clean image.
dataloader.py is the dataloader

**Comment by SB2020-eye** [comment]
I see dataloader.py now. I'm so sorry! I must have been tired or something. Thank you.

So, if my image is "imageA.png", what do I do with the pickle and dataloader files to binarize it?

**Comment by amandpkr** [comment]
As you are new to coding, I suggest you first run the original code.

**Comment by SB2020-eye** [comment]
Thank you, @VIROBO-15, for bearing with me thus far. I hesitate to tell you, but I don't even know how to first run the original code. I know this isn't a tutorial forum, so I understand if you want to pass on spelling it out for me. :)

I know how to run things like opencv's or skimage's versions of thresholding or binarization, if that helps. But I'm just lost as to where to begin with UDBNET. I'm not sure where to plug in my `path to image` for example. I'm not sure what to "run." Lol.
